kes/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    url(r'cart_remove=', views.removeCart),
    url(r'cart_add=', views.addCart),
    url(r'request_email', views.send_email),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^shop/', include('shop.urls', namespace='shop')),
    url(r'^contacts/$', TemplateView.as_view(template_name='contacts.html'), name='contacts'),
    url(r'^building/', include('building.urls', namespace='building')),
    url(r'^checkout/', include('checkout.urls')),
    url(r'^admin/', admin.site.urls),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='shop/shop.html'), name='home'),
    url(r'^(?P<slug>[-*\w]+)/', include([
        url(r'^$', views.categoryPage),
        url(r'^search=', views.searchItems),
        url(r'^sort=', views.sortItems),
        url(r'^(?P<slug>[-*\w]+)/$', views.itemPage),
    ])),
]

templates/base/footer.html
<div class="footer__wrapper">
  <address class="footer__item footer-adds">
    <h3 class="footer-adds__h3">КазЭнергоСтрой</h3>
    <span class="footer-adds__address">г. Казань, ул. М.Гафури, д. 50, пом. 2</span><br>
    <div class="footer-adds__tels">
      <p class="footer-adds__tel">240-00-26</p>
      <p class="footer-adds__tel">240-57-26</p>
    </div>
  </address>
  <section class="footer__item footer-social">
    <h3 class="footer-social__h3 footer__h3">давайте дружить!</h3>
    <div class="footer-social__wrapper">
      <a href="" class="footer-social__link footer-social__link--vk"></a>
      <a href="" class="footer-social__link footer-social__link--fb"></a>
      <a href="" class="footer-social__link footer-social__link--inst"></a>
    </div>
  </section>
  <section class="footer__item footer-develop">
    <h3 class="footer-develop__created footer__h3">разработано:</h3>
    <a href="" class="footer-develop__company">albert-studio-entertainment.com</a>
  </section>
</div>

templates/base/head.html
{% load staticfiles %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<link href="https://fonts.googleapis.com/css?family=PT+Sans:400,700&amp;subset=cyrillic" rel="stylesheet">
<meta name="format-detection" content="telephone=no">
<script src="{% static 'static/js/jquery.js' %}"></script>
<link rel="stylesheet" href="{% static 'static/css/normalize.css' %}">
<link rel="stylesheet" href="{% static 'static/css/style.css' %}">

templates/base/header.html
{% load staticfiles %}
<div class="info">
  <a href="{% url 'index' %}">
    <picture>
      <source media="(max-width: 767px)" srcset="{% static 'static/img/index/logo-m-1.png' %}">
      <img class="info__logo" src="{% static 'static/img/index/logo-l-1.png' %}"
           alt="строительная компания казэнергострой" width="250">
    </picture>
  </a>
  <div class="info__radio">
    <span class="info__span info__span--header">Lorem ipsum.</span>
    <span class="info__tel">240-00-26</span>
    <span class="info__span info__span--footer">Работаем с 9:00 до 19:00</span>
  </div>
  <div class="info__radio">
    <span class="info__span info__span--header">Lorem ipsum dolor sit.</span>
    <span class="info__tel">240-57-26</span>
    <span class="info__span info__span--footer">Lorem ipsum dolor.</span>
  </div>
  <button class="info__btn btn" type="button" name="button">Оставить заявку</button>
</div>
<div class="main-nav">
  <nav class="main-nav__navigation">
    <button type="button" class="main-nav__toggle">
      <span class="main-nav__toggle-bar main-nav__toggle-bar-top"></span>
      <span class="main-nav__toggle-bar main-nav__toggle-bar-middle"></span>
      <span class="main-nav__toggle-bar main-nav__toggle-bar-bottom"></span>
    </button>
    <div class="main-nav__wrapper">
      <ul class="main-nav__items">
        <li class="main-nav__item"><a class="main-nav__link" href="{% url 'index' %}">главная</a></li>
        <li class="main-nav__item main-nav__item--submenu">
          <a class="main-nav__link" href="{% url 'building:home' %}">строительство</a>
          <ul class="main-nav__submenu">
            {% for itemBuilding in itemsBuilding %}
              <li class="main-nav__subitem">
                <a href="{{ itemBuilding.url }}" class="main-nav__sublink">{{ itemBuilding.nameInMenu }}</a>
              </li>
            {% endfor %}
          </ul>
        </li>
        <li class="main-nav__item main-nav__item--submenu">
          <a class="main-nav__link" href="{% url 'shop:home' %}">магазин</a>
          <ul class="main-nav__submenu">
            {% for itemCategory in itemsCategory %}
              <li class="main-nav__subitem">
                <a href="{{ itemCategory.url }}" class="main-nav__sublink">{{ itemCategory.name }}</a>
              </li>
            {% endfor %}
          </ul>
        </li>
        <li class="main-nav__item"><a class="main-nav__link" href="#">"коломаки"</a></li>
        <li class="main-nav__item"><a class="main-nav__link" href="{% url 'contacts' %}">контакты</a></li>
      </ul>
    </div>
    <button type="button" class="main-nav__cart">
      {% if totalItemsInCart %}
        {% if totalItemsInCart != 0 %}
          <span class="main-nav__num-cart">{{ totalItemsInCart }}</span>
        {% endif %}
      {% endif %}
    </button>

    <ul class="cart">
      {% if itemsInCart %}
        {% for itemInCart in itemsInCart %}
          <li class="cart__item">
            <a href="{{ itemInCart.url }}" class="cart__link">
              <span class="cart__title-item">{{ forloop.counter }}:</span>
              {% if itemInCart.nmb != 1 %}
                <span class="cart__name">{{ itemInCart.name }} (<small>x</small>{{ itemInCart.nmb }})</span><br>
              {% else %}
                <span class="cart__name">{{ itemInCart.name }}</span><br>
              {% endif %}
              <span class="cart__price">{{ itemInCart.price }} руб.</span>
            </a>
            <button type="submit" class="cart__remove" data-url="{{ itemInCart.url }}"></button>
          </li>
        {% endfor %}
      {% endif %}
      <li class="cart__item cart__item--total">
        <span class="cart__title-item cart__title-item--1">Товаров:</span>
        <span class="cart__total-item">
              {% if totalItemsInCart %}
                {{ totalItemsInCart }}
              {% else %}
                0
              {% endif %}
            </span><br>
        <span class="cart__title-item cart__title-item--2">Итого:</span>
        <span class="cart__total-price">
              {% if totalPriceInCart %}
                {{ totalPriceInCart }} руб.
              {% else %}
                0 руб.
              {% endif %}
            </span><br>
        <a href="{% url 'checkout' %}">
          <button type="button" class="cart__btn btn">оформить заказ</button>
        </a>
      </li>
    </ul>
  </nav>
</div>

templates/base/popup-request.html
<div class="popup-request">
  <button class="popup-request__close" type="button" title="закрыть"></button>
  <h2 class="popup-request__h2">форма обратной связи</h2>
  <p class="popup-request__thanks hidden">Спасибо, в ближайшее время мы с вами свяжемся</p>
  <form class="popup-request__form" id="feedbackForm" method="post">
    {% csrf_token %}
    <label class="popup-request__label">
      <span class="popup-request__item">Имя:</span>
      <input class="popup-request__btn" id="feedbackName" type="text" name="name" required>
    </label>
    <label class="popup-request__label">
      <span class="popup-request__item">телефон:</span>
      <input class="popup-request__btn" type="tel" name="tel">
    </label>
    <label class="popup-request__label">
      <span class="popup-request__item">почта:</span>
      <input class="popup-request__btn" id="feedbackEmail" type="email" name="email" required>
    </label>
    <label class="popup-request__label">
      <span class="popup-request__item">сообщение:</span>
      <textarea rows="3" class="popup-request__btn popup-request__textarea" type="text" name="message"></textarea>
    </label>
    <input class="popup-request__submit btn" id="feedbackSubmit" type="submit" value="ОТПРАВИТЬ ЗАЯВКУ">
  </form>
</div>
<div class="overlay"></div>