kes/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    url(r'cart_remove=', views.removeCart),
    url(r'cart_add=', views.addCart),
    url(r'request_email', views.send_email),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^shop/', include('shop.urls', namespace='shop')),
    url(r'^contacts/$', TemplateView.as_view(template_name='contacts.html'), name='contacts'),
    url(r'^building/', include('building.urls', namespace='building')),
    url(r'^checkout/', include('checkout.urls')),
    url(r'^admin/', admin.site.urls),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='shop/shop.html'), name='home'),
    url(r'^(?P<slug>[-*\w]+)/', include([
        url(r'^$', views.categoryPage),
        url(r'^search=', views.searchItems),
        url(r'^sort=', views.sortItems),
        url(r'^(?P<slug>[-*\w]+)/$', views.itemPage),
    ])),
]

shop/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(blank=True, null=True, max_length=100, verbose_name='Название')
    slug = models.SlugField(blank=True, null=True, verbose_name='Название в url')
    url = models.CharField(blank=True, null=True, max_length=100, editable=False)
    descr = models.TextField(blank=True, null=True, max_length=5000, verbose_name='Небольшое описание')
    title = models.CharField(blank=True, null=True, max_length=100, verbose_name='Тег title')
    text = models.TextField(blank=True, null=True, max_length=5000, verbose_name='Текст страницы')

    propPrice = models.BooleanField(default=False, verbose_name='Свойство - цена')
    propManufacturer = models.BooleanField(default=False, verbose_name='Свойство - производитель')
    propType = models.BooleanField(default=False, verbose_name='Свойство - тип')
    propPower = models.BooleanField(default=False, verbose_name='Свойство - мощность (кВт)')
    propAmount = models.BooleanField(default=False, verbose_name='Свойство - объем парильни')

    def save(self, *args, **kwargs):
        self.url = '/shop/' + self.slug
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория интернет-магазина'
        verbose_name_plural = 'Категории интернет-магазина'


# -------------------------------------------------CHOICES---------------------------------------------------------------

CHOICES_TYPE = (
    ('Печи', (
        ('Wood', 'Дровяная'),
        ('Electrical', 'Электрическая')
    )),
    ('Двери', (
        ('Sauna', 'Для сауны и бани'),
        ('Hamam', 'Для хамама и моечной'),
        ('Interior', 'Межкомнатные')
    ))
)

CHOICES_MANUFACTURER = (
        ('Harvia', 'Harvia'),
        ('Tylo', 'Tylo')
    )

# -----------------------------------------------END_CHOICES-------------------------------------------------------------


class Item(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    name = models.CharField(blank=True, null=True, max_length=100, verbose_name='Название')
    slug = models.SlugField(blank=True, null=True, editable=False)
    url = models.CharField(blank=True, null=True, max_length=100, editable=False)
    manufacturer = models.CharField(max_length=100, choices=CHOICES_MANUFACTURER, blank=True, null=True,
                                    verbose_name='Производитель')
    type = models.CharField(blank=True, null=True, max_length=100, choices=CHOICES_TYPE, verbose_name='Тип')
    price = models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена')
    power = models.FloatField(blank=True, null=True, verbose_name='Мощность')
    minAmount = models.FloatField(blank=True, null=True, verbose_name='мин. объем парильни')
    maxAmount = models.FloatField(blank=True, null=True, verbose_name='макс. объем парильни')
    description = models.TextField(blank=True, null=True, verbose_name='описание')
    image = models.ImageField(upload_to='item', blank=True, null=True, verbose_name='картинка')

    def save(self, *args, **kwargs):
        super(Item, self).save(*args, **kwargs)
        self.slug = self.name.replace(' ', '_').lower() + '-' + str(self.id)
        self.url = '/shop/' + self.category.slug + '/' + self.slug
        super(Item, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

shop/views.py
from itertools import chain
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from .models import Category, Item, CHOICES_TYPE as categoriesModelT
from .funcs import getItems



def categoryPage(request, slug):
    categoryModel = get_object_or_404(Category, slug=slug)
    categoryName = categoryModel.name

    for categoryModelT in categoriesModelT:
        if categoryModelT[0] == categoryName:
            typesModel = categoryModelT[1]
            break
    else:
        typesModel = None

    return render(request, 'shop/categoryShop.html', {'categoryModel': categoryModel,
                                                      'typesModel': typesModel})


def searchItems(request, slug):
    if request.method == 'GET':
        search = request.GET.get('search')
        page = request.GET.get('page')

        if search == '':
            sortItems = Item.objects.filter(category__slug=slug)

        else:
            sortItems = Item.objects.filter(category__slug=slug).filter(name__icontains=search)

        data = getItems(sortItems, page)

        return JsonResponse(data)


def sortItems(request, slug):
    if request.method == 'GET':

        sortItems = Item.objects.filter(category__slug=slug)

        if request.GET.getlist('manufacturer'):
            manufacturers = request.GET.getlist('manufacturer')
            sortItems = sortItems.filter(manufacturer__in=manufacturers)

        if request.GET.getlist('type'):
            types = request.GET.getlist('type')
            sortItems = sortItems.filter(type__in=types)

        if request.GET.get('minPrice'):
            minPrice = request.GET.get('minPrice')
            sortItems = sortItems.filter(price__gte=minPrice)

        if request.GET.get('maxPrice'):
            maxPrice = request.GET.get('maxPrice')
            sortItems = sortItems.filter(price__lte=maxPrice)

        if request.GET.get('minPower'):
            minPower = request.GET.get('minPower')
            sortItems = sortItems.filter(power__gte=minPower)

        if request.GET.get('maxPower'):
            maxPower = request.GET.get('maxPower')
            sortItems = sortItems.filter(power__lte=maxPower)

        if request.GET.get('amount'):
            amount = request.GET.get('amount')
            sortItems = sortItems.filter(beforeAmount__lte=amount).filter(afterAmount__gte=amount)

        page = request.GET.get('page')

        data = getItems(sortItems, page)

        return JsonResponse(data)



def itemPage(request, slug):
    itemModel = get_object_or_404(Item, slug=slug)
    ignoreItems = Item.objects.exclude(slug=itemModel.slug)

    if hasattr(itemModel, 'type'):
        ignoreItems = ignoreItems.filter(type=itemModel.type)

    cognateItems = ignoreItems.order_by('price', 'pk').filter(price__gte=itemModel.price)[:3]
    if cognateItems.count() != 3:
        for i in range(3):
            j = 3 - i
            if cognateItems.count() == i:
                beforeItems = ignoreItems.order_by('-price', 'pk').filter(price__lt=itemModel.price)[:j]
                cognateItems = list(chain(cognateItems, beforeItems))
                break

    return render(request, 'shop/item.html', {'item': itemModel,
                                              'cognateItems': cognateItems})

templates/shop/categoryShop.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="ru">
<head>
  <title>{{ categoryModel.title }}</title>
  {% include 'base/head.html' %}
</head>
<body>
<header class="header">
  {% include 'base/header.html' %}
</header>
<main>
  <div class="page-header">
    <div class="page-header__header text-header">
      <h1 class="page-header__h text-h">{{ categoryModel.name }}</h1>
    </div>
    <p class="page-header__descr">{{ categoryModel.text }}</p>
  </div>
  <form action="search=" method="get" class="search" id="search">
    <input type="search" class="search__result" name="search" placeholder="поиск">
    <button type="submit" class="search__submit"></button>
  </form>
  <form action="sort=" method="get" class="filter" id="filter">
    <div class="filter__header">
      <h2 class="filter__h2">фильтры</h2>
      <img class="filter__arrow" src="{% static 'static/img/shop/arrow.png' %}" width="30" height="32"
           alt="arrow">
    </div>
    <div class="filter__fieldsets" style="display: none">
      {% if categoryModel.propManufacturer %}
        <fieldset class="filter__fieldset">
          <p class="filter__legend">производитель:</p>
          <div class="filter__wrapper">
            <label class="filter__item">
              <input type="checkbox" class="filter__checkbox" name="manufacturer" value="Harvia">
              <i class="filter__checkbox--check"></i>
              <span class="filter__span">Harvia</span>
            </label>
            <label class="filter__item">
              <input type="checkbox" class="filter__checkbox" name="manufacturer" value="Tylo">
              <i class="filter__checkbox--check"></i>
              <span class="filter__span">Tylo</span>
            </label>
          </div>
        </fieldset>
      {% endif %}

      {% if categoryModel.propType %}
        <fieldset class="filter__fieldset">
          <p class="filter__legend">тип:</p>
          <div class="filter__wrapper">
            {% for typeModel in typesModel %}
              <label class="filter__item filter__item--type">
                <input type="checkbox" class="filter__checkbox" name="type" value="{{ typeModel.0 }}">
                <i class="filter__checkbox--check"></i>
                <span class="filter__span">{{ typeModel.1 }}</span>
              </label>
            {% endfor %}
          </div>
        </fieldset>
      {% endif %}

      {% if categoryModel.propPrice %}
        <fieldset class="filter__fieldset">
          <p class="filter__legend">цена (руб.):</p>
          <div class="filter__wrapper">
            <label class="filter__item filter__item--number">
              <span class="filter__span">от:</span>
              <input type="number" class="filter__number" name="minPrice" min="0">
            </label>
            <label class="filter__item filter__item--number">
              <span class="filter__span">до:</span>
              <input type="number" class="filter__number" name="maxPrice" min="0">
            </label>
          </div>
        </fieldset>
      {% endif %}

      {% if categoryModel.propPower %}
        <fieldset class="filter__fieldset">
          <p class="filter__legend">мощность (кв.):</p>
          <div class="filter__wrapper">
            <label class="filter__item filter__item--number">
              <span class="filter__span">от:</span>
              <input type="number" class="filter__number" name="minPower" min="0">
            </label>
            <label class="filter__item filter__item--number">
              <span class="filter__span">до:</span>
              <input type="number" class="filter__number" name="maxPower" min="0">
            </label>
          </div>
        </fieldset>
      {% endif %}

      {% if categoryModel.propAmount %}
        <fieldset class="filter__fieldset">
          <p class="filter__legend">объем парильни (м<sup>3</sup>):</p>
          <div class="filter__wrapper filter__wrapper--amount">
            <label class="filter__item filter__item--number">
              <input type="number" class="filter__number filter__number--amount" name="amount" min="0">
            </label>
          </div>
        </fieldset>
      {% endif %}
      <fieldset class="filter__fieldset filter__fieldset--submit">
        <button type="submit" class="filter__submit btn">Показать</button>
      </fieldset>
    </div>
  </form>
  <div class="result-container">
  </div>
  <button class="paginator btn" type="submit" value="2">показать еще</button>
</main>
<footer class="footer">
  {% include 'base/footer.html' %}
</footer>
{% include 'base/popup-request.html' %}
<script src="{% static 'static/js/header.js' %}"></script>
<script src="{% static 'static/js/shop/itemsShop.js' %}"></script>
</body>
</html>

templates/shop/item.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="ru">
<head>
  <title>Document</title>
  {% include 'base/head.html' %}
</head>
<body>
<header class="header">
  {% include 'base/header.html' %}
</header>
<main>
  <div class="item-page">
    <h1 class="item-page__title">{{ item.name }}</h1>
    <div class="item-page__info">
      <div class="item-page__img"></div>
      <!-- <img src="" alt="" class="item__img"> -->
      <section class="item-page__section item-page__section--price">
        <span class="item-page__section-title">Цена:</span>
        <span class="item-page__price">{{ item.price }} руб.</span>
        <form action="cart_add=" method="get" class="item-page__form-buy" data-slug="{{ item.url }}"
              data-name="{{ item.name }}" data-price="{{ item.price }}">
          <button type="submit" class="item-page__btn btn">Добавить в корзину</button>
        </form>
      </section>
      <section class="item-page__section item-page__section--details">
        <span class="item-page__section-title">основные характеристики:</span>
        {% if item.manufacturer %}
          <span class="item-page__detail">Производитель: &ensp; {{ item.manufacturer }}</span>
        {% endif %}
        {% if item.type %}
          <span class="item-page__detail">Тип: &ensp; {{ item.get_type_display }}</span>
        {% endif %}
        {% if item.power %}
          <span class="item-page__detail">Мощность: &ensp; {{ item.power }} кВт</span>
        {% endif %}
        {% if item.beforeAmount and item.afterAmount %}
          <span
              class="item-page__detail">Объем: &ensp; {{ item.beforeAmount }}м<sup>3</sup> - {{ item.afterAmount }}м<sup>3</sup></span>
        {% endif %}
      </section>
      <section class="item-page__section item-page__section--descr">
        <span class="item-page__section-title">Описание:</span>
        <p class="item-page__detail">{{ item.description }}</p>
      </section>
    </div>
  </div>
  <div class="cognate-items">
    <h2 class="cognate-items__title">Похожие товары:</h2>
    <div class="cognate-items__wrapper">
      {% for cognateItem in cognateItems %}
      <a href="{{ cognateItem.fullSlug }}" class="product">
        <h2 class="product__title">{{ cognateItem.name }}</h2>
        <div class="product__info">
          <div class="product__img"></div>
          <div class="product__wrapper">
            {% if cognateItem.power %}
              <span class="product__power">Мощность: {{ cognateItem.power }}кВт</span>
            {% endif %}
            {% if cognateItem.beforeAmount and cognateItem.afterAmount %}
              <span class="product__amount">Объем: {{ cognateItem.beforeAmount }}м<sup>3</sup> - {{ cognateItem.afterAmount }}м<sup>3</sup></span>
            {% endif %}
            {% if cognateItem.price %}
              <span class="product__price">Цена: {{ cognateItem.price }} руб.</span>
            {% endif %}
            <form action="cart_add=" class="product__buy" method="get" data-slug="{{ cognateItem.fullSlug }}"
                  data-name="{{ cognateItem.name }}" data-price="{{ cognateItem.price }}">
              <button type="submit" class="product__add-cart btn">добавить в корзину</button>
            </form>
          </div>
        </div>
      </a>
    {% endfor %}
    </div>
  </div>
</main>
<footer class="footer">
  {% include 'base/footer.html' %}
</footer>
{% include 'base/popup-request.html' %}
<script src="{% static 'static/js/header.js' %}"></script>
<script src="{% static 'static/js/shop/item.js' %}"></script>
</body>
</html>

templates/shop/shop.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="ru">
<head>
  <title>Document</title>
  {% include 'base/head.html' %}
</head>
<body>
<header class="header">
  {% include 'base/header.html' %}
</header>
<main>
  <div class="page-header">
    <div class="page-header__header text-header">
      <h1 class="page-header__h text-h">Магазин</h1>
    </div>
    <p class="page-header__descr">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae consectetur corporis
      culpa
      cumque distinctio, dolorem doloribus eaque expedita facere incidunt ipsam libero minus nisi officiis, perspiciatis
      quam tempora! Ad, animi aperiam architecto dolorum ea, eos esse excepturi expedita iusto labore laudantium nihil
      nisi obcaecati quis reiciendis rem repudiandae saepe suscipit?</p>
  </div>
  <div class="page-info">
    <div class="page-info__header text-header">
      <h2 class="page-info__h text-h">Мы продаем:</h2>
    </div>
    <div class="page-info__wrapper">
        {% for itemCategory in itemsCategory %}
            <section class="page-info__item">
                <a class="page-info__link" href="{{ itemCategory.url }}">
                    <h3 class="page-info__title">{{ itemCategory.name }}</h3>
                    {#                        <img src="" alt="" class="page-info__img">#}
                    <div class="page-info__img"></div>
                    <p class="page-info__descr">{{ itemCategory.descr }}</p>
                </a>
            </section>
        {% endfor %}
    </div>
  </div>
</main>
<footer class="footer">
  {% include 'base/footer.html' %}
</footer>
{% include 'base/popup-request.html' %}
<script src="{% static 'static/js/header.js' %}"></script>
</body>
</html>